branches:
  only:
  - ci
before_build:
  - nuget restore
configuration: Release
build:
  project: ClearBank.DeveloperTest.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - ClearBank.DeveloperTest.Tests.dll
