branches:
  only:
  - ci

configuration: Release

before_build:
  - nuget restore

build:
  project: ClearBank.DeveloperTest.sln
  verbosity: minimal

environment:
    COVERALLS_REPO_TOKEN:
      secure: UnarH7WXjJ9BZqU8ToW789/uSgjSna9HSpB6rITOfiL9v6HNHyioNmCiUA0YggYt  

after_test:
  - cmd: .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:nunit3-console.exe "-targetargs:""ClearBank.DeveloperTest.Tests\bin\Release\ClearBank.DeveloperTest.Tests.dll""" -register:user -filter:"+[ClearBank.DeveloperTest*]* -[ClearBank.DeveloperTest.Test]*" -output:coverage.xml
  - cmd: .\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml --repo-token %COVERALLS_REPO_TOKEN%